name: Run tests

on: [push, pull_request]

jobs:
  test:
    name: Run tests and linting
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: bracketclub-test
          POSTGRES_DB: bracketclub-test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: |
          npm install

      - name: Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm test
